## Programming Practice (2.1 to 2.4)

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# 2.1
A = torch.rand(5, 5)
B = torch.rand(5, 5)
C = torch.zeros_like(A)

addition = A + B
subtraction = A - B
ele_multiplication = A * B             
mat_multiplication = torch.matmul(A, B)

print("Tensor A:\n", A)
print("Tensor B:\n", B)
print("Zero Tensor C:\n", C)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", ele_multiplication)
print("Matrix Multiplication:\n", mat_multiplication)

Tensor A:
 tensor([[0.5826, 0.7521, 0.0472, 0.5642, 0.6244],
        [0.7300, 0.3634, 0.8037, 0.4770, 0.8271],
        [0.8854, 0.1753, 0.9595, 0.5884, 0.6687],
        [0.0963, 0.1366, 0.0966, 0.6443, 0.2709],
        [0.7342, 0.4258, 0.1711, 0.7213, 0.9813]])
Tensor B:
 tensor([[0.3330, 0.2005, 0.4355, 0.2754, 0.4639],
        [0.1488, 0.2876, 0.8525, 0.7896, 0.9441],
        [0.9076, 0.5084, 0.5241, 0.4222, 0.6130],
        [0.6129, 0.9010, 0.1791, 0.5243, 0.8253],
        [0.4488, 0.1451, 0.8802, 0.1865, 0.2502]])
Zero Tensor C:
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Addition:
 tensor([[0.9156, 0.9526, 0.4827, 0.8396, 1.0883],
        [0.8788, 0.6509, 1.6562, 1.2666, 1.7711],
        [1.7929, 0.6836, 1.4836, 1.0105, 1.2817],
        [0.7092, 1.0376, 0.2756, 1.1686, 1.0962],
        [1.1829, 0.5709, 1.0513, 0.9078, 1.2315]])
Subtraction:
 tensor([[ 0.2496,  0.5516, -0.388

In [3]:
# 2.2
A = torch.rand(6, 4)
A_reshaped = A.reshape(24)
A_subset = A[1:5, 1:3]

print("Original tensor:\n", A)
print("Reshaped tensor:\n", A_reshaped)
print("Sub-tensor:\n", A_subset)

Original tensor:
 tensor([[0.6970, 0.6236, 0.6444, 0.3296],
        [0.7340, 0.6093, 0.6697, 0.9761],
        [0.7351, 0.5742, 0.5518, 0.0871],
        [0.8246, 0.4457, 0.3832, 0.0012],
        [0.5533, 0.1285, 0.3277, 0.1273],
        [0.9087, 0.9495, 0.8325, 0.6995]])
Reshaped tensor:
 tensor([0.6970, 0.6236, 0.6444, 0.3296, 0.7340, 0.6093, 0.6697, 0.9761, 0.7351,
        0.5742, 0.5518, 0.0871, 0.8246, 0.4457, 0.3832, 0.0012, 0.5533, 0.1285,
        0.3277, 0.1273, 0.9087, 0.9495, 0.8325, 0.6995])
Sub-tensor:
 tensor([[0.6093, 0.6697],
        [0.5742, 0.5518],
        [0.4457, 0.3832],
        [0.1285, 0.3277]])


In [4]:
# 2.3
A = torch.rand(3, 3, requires_grad=True)
B = torch.tensor([[1., 0., 2.],
                  [1., 1., 0.],
                  [0., 3., 1.]])
C = A * B
S = C.sum()
S.backward()

print("Tensor A:\n", A)
print("Tensor B:\n", B)
print("A*B:\n", C)
print("Sum of elements:\n", S.item())
print("Gradient of S w.r.t A:\n", A.grad)

Tensor A:
 tensor([[0.4740, 0.9721, 0.7155],
        [0.7938, 0.7656, 0.9314],
        [0.3438, 0.3883, 0.7666]], requires_grad=True)
Tensor B:
 tensor([[1., 0., 2.],
        [1., 1., 0.],
        [0., 3., 1.]])
A*B:
 tensor([[0.4740, 0.0000, 1.4311],
        [0.7938, 0.7656, 0.0000],
        [0.0000, 1.1649, 0.7666]], grad_fn=<MulBackward0>)
Sum of elements:
 5.396053314208984
Gradient of S w.r.t A:
 tensor([[1., 0., 2.],
        [1., 1., 0.],
        [0., 3., 1.]])


## Simple Linear Regression Model (2.5)

In [ ]:
    torch.manual_seed(42)
N = 256
x = torch.linspace(-2, 2, N).unsqueeze(1)
true_m, true_b = 3.0, 0.7
y = true_m * x + true_b + 0.2 * torch.randn_like(x)

class SimpleLinear(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(1, 1) 
    def forward(self, x):
        return self.fc(x)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = SimpleLinear().to(device)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.05)

model.train()
data, target = x.to(device), y.to(device)

optimizer.zero_grad()
output = model(data)
loss = criterion(output, target)
loss.backward()
optimizer.step()                    

m_learned = model.fc.weight.item()
b_learned = model.fc.bias.item()
print(f"MSE Training loss after 1 epoch: {loss.item()}")
print(f"Learned params: w={m_learned}, b={b_learned}")

save_path = "weights.pt"
torch.save(model.state_dict(), save_path)
print(f"Saved weights to: {save_path}")

new_model = SimpleLinear().to(device)
new_model.load_state_dict(torch.load(save_path, map_location=device))
new_model.eval()

with torch.no_grad():
    test_x = torch.tensor([[-1.5], [0.0], [1.5]]).to(device)
    test_y_hat = new_model(test_x)
print(f"True params: w={true_m}, b={true_b}")
print("Predictions for x=[-1.5, 0.0, 1.5]:", test_y_hat.squeeze().cpu().numpy())
print(f"Actual y values: {true_m * test_x.squeeze().cpu().numpy() + true_b}")


MSE Training loss after 1 epoch: 10.019256591796875
Learned params: w=0.8872767686843872, b=-0.5553232431411743
Saved weights to: weights.pt
True params: w=3.0, b=0.7
Predictions for x=[-1.5, 0.0, 1.5]: [-1.8862385  -0.55532324  0.77559197]
Actual y values: [-3.8  0.7  5.2]


C:\Users\allan\AppData\Local\Temp\ipykernel_13308\3783492734.py:38: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  new_model.load_state_dict(torch.load(save_path, map_locatio